import * as Capability from './runtime-capability-identifiers'
export * from './runtime-capability-identifiers'
import { AGENT_SESSION_BACKGROUND_TASK_CHILD_VIEWS_CAPABILITY } from './agent-session-background-task-child-views-capability'
import { REMOTE_SERVER_UPDATE_CAPABILITY } from './remote-server-update'
import {
  SKILL_BUNDLE_INSTALL_CAPABILITY,
  SKILL_DELETE_CAPABILITY,
  SKILL_INSTALL_CAPABILITY,
  SKILL_INSTALL_CANCEL_CAPABILITY,
  SKILL_INSTALL_PROGRESS_CAPABILITY,
  SKILL_INSTALL_PROVIDERS_CAPABILITY,
  SKILL_INSTALL_RESULT_V2_CAPABILITY,
  SKILL_MANAGEMENT_CAPABILITY,
  SKILL_UPLOAD_CAPABILITY
} from './skill-install-capability'
export { SKILL_INSTALL_RESULT_V2_CAPABILITY } from './skill-install-capability'

// Why: declares the Orca runtime RPC compatibility contract. Desktop,
// headless server, CLI, and mobile builds may drift in app version, but
// they must agree on this protocol range before runtime RPCs are allowed.
//
// Bump RUNTIME_PROTOCOL_VERSION when:
//   - You remove an RPC method or required parameter that clients use.
//   - You change the meaning (units, nullability) of an existing field
//     clients read.
//   - You change encrypted framing, terminal stream framing, or auth.
// Do NOT bump for:
//   - Adding new RPC methods.
//   - Adding new optional fields on existing methods.
//   - Adding new ignorable event types.
//
// Bump MIN_COMPATIBLE_RUNTIME_CLIENT_VERSION when a runtime server must
// refuse older clients. Bump MIN_COMPATIBLE_RUNTIME_SERVER_VERSION when
// this client build requires a newer server. Exact app-version equality is
// never required; these numbers define the supported compatibility window.

export const RUNTIME_PROTOCOL_VERSION = 3
export const MIN_COMPATIBLE_RUNTIME_CLIENT_VERSION = 2
export const MIN_COMPATIBLE_RUNTIME_SERVER_VERSION = 2

// Generic native clients include the CLI and must not claim Electron-only page
// placement support.
export const NATIVE_REMOTE_RUNTIME_CLIENT_CAPABILITIES = [
  Capability.SESSION_TAB_CLOSE_INTENT_RUNTIME_CAPABILITY,
  Capability.AGENT_SESSION_BOUNDARY_RUNTIME_CAPABILITY,
  Capability.WORKTREE_VISIBILITY_DEFAULTS_RUNTIME_CAPABILITY,
  Capability.WORKTREE_VISIBILITY_SOURCE_DEFAULTS_RUNTIME_CAPABILITY,
  Capability.WORKTREE_GITHUB_PR_SUPPRESSION_RUNTIME_CAPABILITY,
  Capability.AUTOMATION_OWNER_FENCING_RUNTIME_CAPABILITY,
  Capability.AUTOMATION_CREATE_IDEMPOTENCY_RUNTIME_CAPABILITY,
  Capability.AGENT_LAUNCH_RUNTIME_CAPABILITY
] as const

// Electron clients can decode client-hosted page placement; becoming a page
// host still requires the separate authenticated browser-client lease.
export const ELECTRON_REMOTE_RUNTIME_CLIENT_CAPABILITIES = [
  ...NATIVE_REMOTE_RUNTIME_CLIENT_CAPABILITIES,
  Capability.AGENT_SESSION_PENDING_SEND_RESULT_RUNTIME_CAPABILITY,
  Capability.AGENT_SESSION_ACCEPTED_SEND_RUNTIME_CAPABILITY,
  Capability.BROWSER_CLIENT_HOST_RUNTIME_CAPABILITY,
  Capability.BROWSER_CLIENT_PAGE_METADATA_RUNTIME_CAPABILITY,
  // Why: only the renderer runs the retirement-proof ledger; CLI and mobile must keep full lists.
  Capability.SESSION_TABS_RETIREMENT_PROOF_DELTA_RUNTIME_CAPABILITY,
  // Only the renderer shows Deleting for a `removing` row; CLI and mobile get those rows omitted.
  Capability.WORKTREE_BACKGROUND_REMOVAL_RUNTIME_CAPABILITY
] as const

export const ANTIGRAVITY_CONFIGURED_MODEL_RUNTIME_CAPABILITY =
  'git.antigravity-configured-model.v1' as const

// Why: `agentSession.create` is a strict object, so an older host refuses a payload carrying the
// reserved `tabId` rather than ignoring it. A client sends the field only to a host advertising this.
export const AGENT_SESSION_CREATE_TAB_ID_RUNTIME_CAPABILITY =
  'agentSession.create.tab-id.v1' as const

export const RUNTIME_CAPABILITIES = [
  AGENT_SESSION_CREATE_TAB_ID_RUNTIME_CAPABILITY,
  ANTIGRAVITY_CONFIGURED_MODEL_RUNTIME_CAPABILITY,
  'files.pathsExist',
  'runtime.status.compat.v1',
  'runtime.environments.v1',
  Capability.REMOTE_RUNTIME_SHARED_CONTROL_CAPABILITY,
  Capability.ORCHESTRATION_FEDERATION_RUNTIME_CAPABILITY,
  Capability.ORCHESTRATION_FEDERATION_CONTROL_MAIL_RUNTIME_CAPABILITY,
  Capability.ORCHESTRATION_FEDERATION_LIFECYCLE_SETTLEMENT_RUNTIME_CAPABILITY,
  Capability.ORCHESTRATION_WORKER_STOP_VERDICT_RUNTIME_CAPABILITY,
  Capability.ORCHESTRATION_WORKER_LAUNCH_PREFERENCES_RUNTIME_CAPABILITY,
  Capability.ORCHESTRATION_FEDERATION_STRUCTURED_READ_RUNTIME_CAPABILITY,
  Capability.ORCHESTRATION_FEDERATION_FLEET_SNAPSHOT_RUNTIME_CAPABILITY,
  Capability.ORCHESTRATION_FEDERATION_RELEASE_ARCHIVE_RUNTIME_CAPABILITY,
  Capability.ORCHESTRATION_CONTRACT_RUNTIME_CAPABILITY,
  Capability.BROWSER_SCREENCAST_RUNTIME_CAPABILITY,
  Capability.BROWSER_TAB_CREATE_KNOWN_ID_RUNTIME_CAPABILITY,
  Capability.BROWSER_CLIENT_HOST_RUNTIME_CAPABILITY,
  Capability.BROWSER_CLIENT_PAGE_METADATA_RUNTIME_CAPABILITY,
  Capability.BROWSER_CLIENT_AUTOMATION_RUNTIME_CAPABILITY,
  Capability.BROWSER_CLIENT_FILE_CHANNEL_RUNTIME_CAPABILITY,
  Capability.BROWSER_NETWORK_TUNNEL_RUNTIME_CAPABILITY,
  Capability.BROWSER_NETWORK_EXECUTION_HOSTS_RUNTIME_CAPABILITY,
  'terminal.binary-stream.v1',
  'terminal.multiplex.v1',
  'workspace-ports.v1',
  'mobile.tasks.v1',
  Capability.PROJECT_HOST_SETUP_RUNTIME_CAPABILITY,
  Capability.TASK_SOURCE_CONTEXT_RUNTIME_CAPABILITY,
  Capability.WORKSPACE_RUN_CONTEXT_RUNTIME_CAPABILITY,
  Capability.WORKTREE_LINKED_WORK_ITEM_CONTEXT_RUNTIME_CAPABILITY,
  Capability.WORKTREE_GITHUB_PR_SUPPRESSION_RUNTIME_CAPABILITY,
  Capability.FOLDER_WORKSPACE_PATH_STATUS_RUNTIME_CAPABILITY,
  Capability.LINEAR_ISSUE_ATTRIBUTE_FILTER_RUNTIME_CAPABILITY,
  Capability.JIRA_USER_FIELDS_RUNTIME_CAPABILITY,
  Capability.AI_VAULT_RUNTIME_CAPABILITY,
  Capability.AI_VAULT_SESSION_TITLES_RUNTIME_CAPABILITY,
  Capability.TERMINAL_QUERY_REPLY_INPUT_RUNTIME_CAPABILITY,
  Capability.TERMINAL_PROMPT_DELIVERY_RUNTIME_CAPABILITY,
  Capability.TERMINAL_PAIRED_PARKING_RUNTIME_CAPABILITY,
  Capability.TERMINAL_QUICK_COMMANDS_RUNTIME_CAPABILITY,
  Capability.WORKTREE_CREATE_IDEMPOTENCY_RUNTIME_CAPABILITY,
  Capability.WORKTREE_ARCHIVE_FAILURE_BLOCKING_RUNTIME_CAPABILITY,
  Capability.TERMINAL_CREATE_IDEMPOTENCY_RUNTIME_CAPABILITY,
  Capability.TERMINAL_CREATE_SHELL_SELECTION_RUNTIME_CAPABILITY,
  Capability.SESSION_TAB_CLOSE_INTENT_RUNTIME_CAPABILITY,
  Capability.SESSION_TABS_AUTHORITATIVE_INVENTORY_RUNTIME_CAPABILITY,
  Capability.SESSION_TABS_SPLIT_GROUP_PLACEMENT_RUNTIME_CAPABILITY,
  Capability.AGENT_SESSION_BOUNDARY_RUNTIME_CAPABILITY,
  REMOTE_SERVER_UPDATE_CAPABILITY,
  Capability.AGENT_SESSION_HOST_AUTHORITY_RUNTIME_CAPABILITY,
  Capability.AGENT_SESSION_OMP_RESUME_PATH_RUNTIME_CAPABILITY,
  Capability.AGENT_SESSION_KEYBOARD_RUNTIME_CAPABILITY,
  Capability.STRUCTURED_AGENT_SESSION_RUNTIME_CAPABILITY,
  Capability.AGENT_SESSION_PENDING_SEND_RESULT_RUNTIME_CAPABILITY,
  // The host side: it accepts a send before any agent has it, and a Stop with no writer before a
  // turn starts, so a client may gate on either.
  Capability.AGENT_SESSION_ACCEPTED_SEND_RUNTIME_CAPABILITY,
  Capability.AGENT_SESSION_CONVERSATION_STOP_RUNTIME_CAPABILITY,
  Capability.STRUCTURED_AGENT_SESSION_HOLD_RUNTIME_CAPABILITY,
  Capability.STRUCTURED_AGENT_SESSION_REVEAL_RUNTIME_CAPABILITY,
  Capability.STRUCTURED_AGENT_SESSION_RESUME_HISTORY_RUNTIME_CAPABILITY,
  Capability.AGENT_SESSION_STATUS_FEED_RUNTIME_CAPABILITY,
  Capability.AGENT_SESSION_TURN_COMPLETION_RUNTIME_CAPABILITY,
  Capability.AGENT_SESSION_REWIND_RUNTIME_CAPABILITY,
  Capability.AGENT_SESSION_CONVERSATION_OUTLINE_RUNTIME_CAPABILITY,
  Capability.AGENT_SESSION_BACKGROUND_TASK_STOP_CAPABILITY,
  Capability.AGENT_SESSION_PROMPT_CANCEL_RUNTIME_CAPABILITY,
  Capability.AGENT_SESSION_QUESTION_ANSWERS_RUNTIME_CAPABILITY,
  Capability.AGENT_SESSION_TURN_ITEM_CAPABILITY,
  Capability.AGENT_SESSION_BACKGROUND_TASK_ROW_STOP_CAPABILITY,
  AGENT_SESSION_BACKGROUND_TASK_CHILD_VIEWS_CAPABILITY,
  Capability.AGENT_SESSION_KIMI_RESUME_RUNTIME_CAPABILITY,
  Capability.AGENT_SESSION_OPENCODE2_RESUME_RUNTIME_CAPABILITY,
  Capability.AGENT_SESSION_MUSE_RESUME_RUNTIME_CAPABILITY,
  Capability.AGENT_SESSION_DSH_RESUME_RUNTIME_CAPABILITY,
  Capability.AGENT_SESSION_QODER_RESUME_RUNTIME_CAPABILITY,
  Capability.AGENT_SESSION_CODEBUDDY_RESUME_RUNTIME_CAPABILITY,
  Capability.AGENT_SESSION_ZCODE_RESUME_RUNTIME_CAPABILITY,
  Capability.FILE_MUTATION_OWNERSHIP_RUNTIME_CAPABILITY,
  Capability.GITHUB_MARK_PR_READY_RUNTIME_CAPABILITY,
  Capability.GITLAB_READY_FOR_REVIEW_RUNTIME_CAPABILITY,
  Capability.WORKTREE_VISIBILITY_DEFAULTS_RUNTIME_CAPABILITY,
  Capability.WORKTREE_VISIBILITY_SOURCE_DEFAULTS_RUNTIME_CAPABILITY,
  Capability.ACCOUNT_IMPORT_RUNTIME_CAPABILITY,
  Capability.EXTERNAL_ACCOUNT_BRIDGE_CAPABILITY,
  Capability.CODEX_RESET_CREDIT_RUNTIME_CAPABILITY,
  SKILL_INSTALL_CAPABILITY,
  SKILL_BUNDLE_INSTALL_CAPABILITY,
  SKILL_INSTALL_CANCEL_CAPABILITY,
  SKILL_INSTALL_PROGRESS_CAPABILITY,
  SKILL_INSTALL_RESULT_V2_CAPABILITY,
  SKILL_UPLOAD_CAPABILITY,
  SKILL_MANAGEMENT_CAPABILITY,
  SKILL_INSTALL_PROVIDERS_CAPABILITY,
  SKILL_DELETE_CAPABILITY,
  Capability.AUTOMATION_LIST_HOST_SCOPE_RUNTIME_CAPABILITY,
  Capability.AUTOMATION_OWNER_FENCING_RUNTIME_CAPABILITY,
  Capability.AUTOMATION_CREATE_IDEMPOTENCY_RUNTIME_CAPABILITY,
  Capability.NOTIFICATIONS_REMOTE_PUSH_RUNTIME_CAPABILITY,
  Capability.AGENT_LAUNCH_RUNTIME_CAPABILITY,
  Capability.AGENT_LAUNCH_REPLAY_RUNTIME_CAPABILITY,
  Capability.AGENT_LAUNCH_REPLAY_REQUIRED_RUNTIME_CAPABILITY
] as const

export type RuntimeCapability = (typeof RUNTIME_CAPABILITIES)[number] | (string & {})

// COMPAT(mobileProtocolAliases): added 2026-05-15 for mobile builds that
// still read desktop/mobile names; remove once mobile reads runtime names.
export const DESKTOP_PROTOCOL_VERSION = RUNTIME_PROTOCOL_VERSION
export const MIN_COMPATIBLE_MOBILE_VERSION = MIN_COMPATIBLE_RUNTIME_CLIENT_VERSION
